service: starter-kit

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1536
  timeout: 180
  # if needed (e.g. upload snapshot)
  iamRoleStatements:
   -  Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource: "*"

functions:
  test-function:
    handler: index.handler
    environment:
      DEBUG: "0"
    events:
      - http:
          path: pdf
          method: get

package:
  artifact: ./package.zip

plugins:
  - serverless-hooks-plugin

resources:
  Resources:
    Screenshots:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: screenshots-debug
    ApiGatewayRestApi:
        Properties:
          BinaryMediaTypes:
          - "*/*"
custom:
  hooks:
    package:initialize:
      - npm run package
